import os
print(dir(os))
#print(help(os.getcwd))
#print(help(os.chdir))
#print(help(os.makedirs))
#print(help(os.mkdir))
#print(help(os.rmdir))
print(help(os.removedirs))
#print(help(os.stat))
#print(help(os.rename))
#print(help(os.walk))